### ISSUE TITLE
Default color for slack

### ISSUE THREAD

**Issue by MuellerSeb** [softwareunderground/badges#1]
Cool badges! I would suggest to use the default logo color for slack (`4A154B`, see: https://simpleicons.org/?q=slack):
```
https://img.shields.io/badge/Swung-Slack-4A154B?style=flat&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABmJLR0QA%2FwD%2FAP%2BgvaeTAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAB3RJTUUH5AYaFSENGSa5qgAABmZJREFUSMeFlltsVNcVhr%2B1z5m7Zzy%2BxaBwcQrGQOpgCAkKtSBQIqJepKhPBULpQ6sKBVWVKqXtSy%2BR0qYXqa2qRmlDCzjBEZGKUCK1TWqlNiGIEKDQBtf4Fki4OIxnxrex53LOXn2YwbjEtOvlHG3tvX%2Btf%2B21%2Fl%2BYJ1QVEbn1vwLYBWwCVgG1lW0ZoA%2FoAQ6LSP%2BdZ%2BeGzAMiIqK%2Bem0GpxNYVeBj3j2b4NCfM2QnfAAaa11al4fZuCZK24owQJ9v%2BbLryIVbd9wVSNUaEWNVtQPYfXHmAD0T32ZJeBM1Q8d0zzMDUpMwAFgLJU%2BxClURw9NfqedLWxMAHSKyR1WNiNhPAM0B6c%2FbdPORTLuOeUMSNkmMBHgyeo32bwwRDMh8bDM%2BZVl0j6uvPrdYknFnSESWzwUzt%2BkyVlUHx7zh5j%2BmPkXBjosjLkWdominiMQ%2BoiEZxuq8OFRXGXJ5K5%2Fde5nha8VlqjooIlZVBcBUiqeqemjGppd1ptfhSpS8pmmN7GVf4whPNY4Di9m%2BMcR03nK3sBbCQeFbv7gBsExVOyp3l6nz1VtjcM4fTK3Uok5IXtPsrHuPevcBXk8d4dWPX6I%2BsIB9wf1s%2B2Y%2FVbFynUIBIeDeplIECiXl5Iv3kbLogogRgbWukfNumT%2FnlYszBxj3hwXg0cQvqXcfYNu5tVyYPE%2B1G8dXn%2BfW72fH49U8sSlOPGr4SccoF4cKs3WzFrY%2BFCMUNmz%2Ba0aeWR1l15JwJ7DaVPpk1YnJ7xIxtQRNjDXRvTx%2F9ef0Tl0g6SYQhAlvmkH%2Fgv74qUaiTSG8ewJ0%2FGgRK5aG8Cts5ouWDa1RxoDRovK9i9MAq1S12QA7b5ROUdBxBIeQ1ACG49m%2FEXPis7Qk3ChHbx6Qw1dgXVeWB7uyDOctP%2Fx6w2zdrIVIyFCyiq8wXlJOZzyAXQbY%2FGGhC8EAilJ%2BVg7ufxU6IAHeSvewfQEadiDuCr%2B6NE1LU4hwUFAF1xFGRkvEjVDlgiPwVqoEsNkAq0ZKp3EIYrFM2xGm7Uc8u%2FzXjHkTmHIHoCiDM73E3IIsDCtRV3gn7QHQ0hTCt0ooKLw%2FWCAM1AcNISOcHSsBrDRAbc7eQMQBFFciHM18kaZIMz3r%2F0HO5mazytsiw%2FmTtCYiGGCkQlltwkEVjMDVmyUA6oIGR%2BDGjAWoM3f2giHAhH%2BFI5nPsDrWxqWNE9S4tUz5k1S7cQ5df4k9S6qY9JRipXtr4w5WQYH0eHkWrqxy8FTn3AvpmFmIqj%2B76EiQjNfHH1JNWFKc3vABj9V9npw%2FRXfmBNsaoTRnRAQDAgqqMJr1KBWUtUmHaR8WRgzAqAH6FgYexqd4R2Yuns5wcLSFK4U36bj%2FdbbUbGdoZoCi3uS%2Bqtt73TlNWygpqXGfZTGXnKesrwkA9BmgZ0noMZT5R0tQ4hzLfo4rhS46W%2F%2BCAn3T7%2BhDySiWMl2RkHArP8dAesKjPixYVbbUBwB6DHB4QWADIamuHPtkhE0t3ZP7ANhe9zgvXP2dfK0pymRJmQLiEYNW6mEVljYGuDzlkwwaHq51AQ4bERkAetvjP2XCT6H480AJeZsB4N7QYt7OnuSROtRXJV2wNNS4qIJvlbUtERJxhxcv5%2FlNWwygV0QGyzKBv%2FP%2ByFfZXf%2ButoR3UuXcS95mKNgxSjpN3qZZFHwUgFPjx5n2c9wo9ktrtcOZtMeWB2NEw4b2thivPLuIS1M%2BAzmrTy4O4ys7Zv1B5fsnVdWCr7PxYf7vej73ex2YeU1VVY9nu7ShG63vRo%2Fe%2FK1%2B518FbXkjo3OjO1XU2LFRzRZ9VdWDczFQ1VsCOHgpd1G%2FcG6jHrj2vPbn%2BjVdHNfr%2BRH92eXva2MPuvxEQpe%2BHdEnzm%2FQf4%2BrRo%2BldMUbGd393oS2dWU0cDSlw1OequrALVG9Q8rLsquqg2OlzLL2Myu1N5eShgB4CjEnSMSJYrX8Oj0t8UH7NMnX0iSDwmhBWRl3tKs9IcmgGRSRZqtqzFwpL4uWWKvWiMjyZKC24%2F1HbsrLn95Pwk3gCpS0yIw%2Fg6clPC2RLc3QmzvJupoARQsvrItxZmtSkkFz6E6Q%2F2m3PFta44jbCaw%2BO3GK7uybnJs8xfXC1fLYCdTz9NIfsCS0mYVhAHp9ZYdr5J%2F%2F127dxUA2AzuBzRUDWVfZlq4YyG6gs9ImdzWQ%2FwFNRlgCFdG5bAAAAABJRU5ErkJggg%3D%3D
```
![swung-slack-gstools](https://img.shields.io/badge/Swung-Slack-4A154B?style=flat&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABmJLR0QA%2FwD%2FAP%2BgvaeTAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAB3RJTUUH5AYaFSENGSa5qgAABmZJREFUSMeFlltsVNcVhr%2B1z5m7Zzy%2BxaBwcQrGQOpgCAkKtSBQIqJepKhPBULpQ6sKBVWVKqXtSy%2BR0qYXqa2qRmlDCzjBEZGKUCK1TWqlNiGIEKDQBtf4Fki4OIxnxrex53LOXn2YwbjEtOvlHG3tvX%2Btf%2B21%2Fl%2BYJ1QVEbn1vwLYBWwCVgG1lW0ZoA%2FoAQ6LSP%2BdZ%2BeGzAMiIqK%2Bem0GpxNYVeBj3j2b4NCfM2QnfAAaa11al4fZuCZK24owQJ9v%2BbLryIVbd9wVSNUaEWNVtQPYfXHmAD0T32ZJeBM1Q8d0zzMDUpMwAFgLJU%2BxClURw9NfqedLWxMAHSKyR1WNiNhPAM0B6c%2FbdPORTLuOeUMSNkmMBHgyeo32bwwRDMh8bDM%2BZVl0j6uvPrdYknFnSESWzwUzt%2BkyVlUHx7zh5j%2BmPkXBjosjLkWdominiMQ%2BoiEZxuq8OFRXGXJ5K5%2Fde5nha8VlqjooIlZVBcBUiqeqemjGppd1ptfhSpS8pmmN7GVf4whPNY4Di9m%2BMcR03nK3sBbCQeFbv7gBsExVOyp3l6nz1VtjcM4fTK3Uok5IXtPsrHuPevcBXk8d4dWPX6I%2BsIB9wf1s%2B2Y%2FVbFynUIBIeDeplIECiXl5Iv3kbLogogRgbWukfNumT%2FnlYszBxj3hwXg0cQvqXcfYNu5tVyYPE%2B1G8dXn%2BfW72fH49U8sSlOPGr4SccoF4cKs3WzFrY%2BFCMUNmz%2Ba0aeWR1l15JwJ7DaVPpk1YnJ7xIxtQRNjDXRvTx%2F9ef0Tl0g6SYQhAlvmkH%2Fgv74qUaiTSG8ewJ0%2FGgRK5aG8Cts5ouWDa1RxoDRovK9i9MAq1S12QA7b5ROUdBxBIeQ1ACG49m%2FEXPis7Qk3ChHbx6Qw1dgXVeWB7uyDOctP%2Fx6w2zdrIVIyFCyiq8wXlJOZzyAXQbY%2FGGhC8EAilJ%2BVg7ufxU6IAHeSvewfQEadiDuCr%2B6NE1LU4hwUFAF1xFGRkvEjVDlgiPwVqoEsNkAq0ZKp3EIYrFM2xGm7Uc8u%2FzXjHkTmHIHoCiDM73E3IIsDCtRV3gn7QHQ0hTCt0ooKLw%2FWCAM1AcNISOcHSsBrDRAbc7eQMQBFFciHM18kaZIMz3r%2F0HO5mazytsiw%2FmTtCYiGGCkQlltwkEVjMDVmyUA6oIGR%2BDGjAWoM3f2giHAhH%2BFI5nPsDrWxqWNE9S4tUz5k1S7cQ5df4k9S6qY9JRipXtr4w5WQYH0eHkWrqxy8FTn3AvpmFmIqj%2B76EiQjNfHH1JNWFKc3vABj9V9npw%2FRXfmBNsaoTRnRAQDAgqqMJr1KBWUtUmHaR8WRgzAqAH6FgYexqd4R2Yuns5wcLSFK4U36bj%2FdbbUbGdoZoCi3uS%2Bqtt73TlNWygpqXGfZTGXnKesrwkA9BmgZ0noMZT5R0tQ4hzLfo4rhS46W%2F%2BCAn3T7%2BhDySiWMl2RkHArP8dAesKjPixYVbbUBwB6DHB4QWADIamuHPtkhE0t3ZP7ANhe9zgvXP2dfK0pymRJmQLiEYNW6mEVljYGuDzlkwwaHq51AQ4bERkAetvjP2XCT6H480AJeZsB4N7QYt7OnuSROtRXJV2wNNS4qIJvlbUtERJxhxcv5%2FlNWwygV0QGyzKBv%2FP%2ByFfZXf%2ButoR3UuXcS95mKNgxSjpN3qZZFHwUgFPjx5n2c9wo9ktrtcOZtMeWB2NEw4b2thivPLuIS1M%2BAzmrTy4O4ys7Zv1B5fsnVdWCr7PxYf7vej73ex2YeU1VVY9nu7ShG63vRo%2Fe%2FK1%2B518FbXkjo3OjO1XU2LFRzRZ9VdWDczFQ1VsCOHgpd1G%2FcG6jHrj2vPbn%2BjVdHNfr%2BRH92eXva2MPuvxEQpe%2BHdEnzm%2FQf4%2BrRo%2BldMUbGd393oS2dWU0cDSlw1OequrALVG9Q8rLsquqg2OlzLL2Myu1N5eShgB4CjEnSMSJYrX8Oj0t8UH7NMnX0iSDwmhBWRl3tKs9IcmgGRSRZqtqzFwpL4uWWKvWiMjyZKC24%2F1HbsrLn95Pwk3gCpS0yIw%2Fg6clPC2RLc3QmzvJupoARQsvrItxZmtSkkFz6E6Q%2F2m3PFta44jbCaw%2BO3GK7uybnJs8xfXC1fLYCdTz9NIfsCS0mYVhAHp9ZYdr5J%2F%2F127dxUA2AzuBzRUDWVfZlq4YyG6gs9ImdzWQ%2FwFNRlgCFdG5bAAAAABJRU5ErkJggg%3D%3D)

Cheers,
Sebastian

PS: maybe one could also reduce the longish logo encoding by using an svg and compress it with `svgo` as described here: https://github.com/badges/shields/blob/master/doc/logos.md

**Comment by stevejpurves** [comment]
cool. how about we add it to the readme page or actually replacing the current slack one....?
also did you already try running this one through `svgo`?

**Comment by MuellerSeb** [comment]
Ok, it didn't get much smaller, but it scales better now ;-)
![swung](https://img.shields.io/badge/Swung-Slack-4A154B?style=flat&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4MDAiIGhlaWdodD0iODAwIj48cGF0aCB0cmFuc2Zvcm09Im1hdHJpeCgxLjEwMjcgMCAwIDEuMTAzMzggLTQxIC00MikiIGQ9Ik0zMDkgNjdhMzQ2IDM0NiAwIDAgMC0yMDAgNTE4YzY1IDIxIDEzMyA0NyAyMDIgMzcgNTYtMTYgNjYtOTUgMjktMTM0LTQzLTUzLTExNS03OC0xNDQtMTQyLTIzLTYzIDIyLTEzNiA4Ny0xNTAgMjgtNCA3OS00IDQ5LTQ1LTgtMjgtMTMtNTctMjMtODR6IiBzdHlsZT0iZmlsbDojOThlOTE2Ii8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNMzM3IDE5NGMtNTgtMy0xMjYgMjgtMTM5IDg5LTEzIDQzIDcgODggNDIgMTE0IDQ0IDQwIDEwOCA2OCAxMjUgMTMxIDExIDQ1LTIwIDEwMi03MSAxMDAtNjAgNC0xMTctMTktMTc0LTM0YTMyOCAzMjggMCAwIDAgMzAzIDE0OWMyOC00IDc5LTQgNTUtNDNMMzQ0IDE5NmMtMS0zLTUtMi03LTJ6IiBzdHlsZT0iZmlsbDojMjRjNDBlIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNMzk1IDU2Yy0yNiA0LTk0LTctNzggMzRsNTAgMTg1YzMxLTYgNjQtMzEgOTQtNyA0MCAzNCAzOSA5MyA0MyAxNDIgMyA1OS0yIDEyMCAxNSAxNzggMjEgNDEgNzYgMjAgMTAwLTggNDEtNDQgMzEtMTA5IDIyLTE2My0xMC01OC0yOS0xMjEtNy0xNzkgMTEtMjcgNTgtNDggMTktNzJBMzQ5IDM0OSAwIDAgMCAzOTUgNTZ6IiBzdHlsZT0iZmlsbDojMzg2MGRkIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNNjc0IDE5NGMtNDAgMzItNTQgODYtNDQgMTM1IDggNzQgNDAgMTUwIDEzIDIyMy0xNiAzOC01NyA2NS05OCA2NC00OS0yMC0zNy04My00My0xMjYtNC02OSA2LTE0NS0zMS0yMDctMjUtMzQtNjgtMjAtOTgtMy0yIDQwIDIwIDg0IDI4IDEyNWw4NyAzMjdhMzQ4IDM0OCAwIDAgMCAyNDEtNDM1Yy0xMy0zNi0zMS03Mi01NS0xMDN6IiBzdHlsZT0iZmlsbDojMWRiNmVkIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJtMzEyIDcyIDE3NCA2NTgiIHN0eWxlPSJmaWxsOm5vbmU7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOjI3O3N0cm9rZS1saW5lY2FwOnJvdW5kIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNMTEwIDU4OGM2NyAxOSAxMzcgNTAgMjA4IDM0IDUyLTIxIDYxLTk3IDI0LTEzNS00Mi01NS0xMTktNzgtMTQ1LTE0NS0xOC02MCAyMS0xMzEgODQtMTQzIDIwLTYgNDEtOCA2Mi03bTI1IDg3YzMzLTE3IDg1LTM1IDEwNyA4IDMzIDU0IDI2IDEyMSAyOSAxODEgMSA0NS0xIDkyIDIwIDEzMiAyOSAzMiA3OCAzIDEwMS0yMyA0MS01MSAyNi0xMjEgMTUtMTc5LTExLTU3LTMwLTEyNCA3LTE3NiA3LTExIDE2LTIwIDI1LTMwIiBzdHlsZT0iZmlsbDpub25lO3N0cm9rZTojZmZmO3N0cm9rZS13aWR0aDozOSIvPjxwYXRoIHRyYW5zZm9ybT0ibWF0cml4KDEuMTAyNyAwIDAgMS4xMDMzOCAtNDEgLTQyKSIgZD0iTTc0NiA0MDBBMzQ2IDM0NiAwIDEgMSAyNTEgODdjMTM3LTYzIDMxOS0zMiA0MTQgOTAgNTEgNjIgODEgMTQyIDgxIDIyM3oiIHN0eWxlPSJmaWxsOm5vbmU7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOjMzO3N0cm9rZS1saW5lY2FwOnJvdW5kIi8+PC9zdmc+)
```
https://img.shields.io/badge/Swung-Slack-4A154B?style=flat&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4MDAiIGhlaWdodD0iODAwIj48cGF0aCB0cmFuc2Zvcm09Im1hdHJpeCgxLjEwMjcgMCAwIDEuMTAzMzggLTQxIC00MikiIGQ9Ik0zMDkgNjdhMzQ2IDM0NiAwIDAgMC0yMDAgNTE4YzY1IDIxIDEzMyA0NyAyMDIgMzcgNTYtMTYgNjYtOTUgMjktMTM0LTQzLTUzLTExNS03OC0xNDQtMTQyLTIzLTYzIDIyLTEzNiA4Ny0xNTAgMjgtNCA3OS00IDQ5LTQ1LTgtMjgtMTMtNTctMjMtODR6IiBzdHlsZT0iZmlsbDojOThlOTE2Ii8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNMzM3IDE5NGMtNTgtMy0xMjYgMjgtMTM5IDg5LTEzIDQzIDcgODggNDIgMTE0IDQ0IDQwIDEwOCA2OCAxMjUgMTMxIDExIDQ1LTIwIDEwMi03MSAxMDAtNjAgNC0xMTctMTktMTc0LTM0YTMyOCAzMjggMCAwIDAgMzAzIDE0OWMyOC00IDc5LTQgNTUtNDNMMzQ0IDE5NmMtMS0zLTUtMi03LTJ6IiBzdHlsZT0iZmlsbDojMjRjNDBlIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNMzk1IDU2Yy0yNiA0LTk0LTctNzggMzRsNTAgMTg1YzMxLTYgNjQtMzEgOTQtNyA0MCAzNCAzOSA5MyA0MyAxNDIgMyA1OS0yIDEyMCAxNSAxNzggMjEgNDEgNzYgMjAgMTAwLTggNDEtNDQgMzEtMTA5IDIyLTE2My0xMC01OC0yOS0xMjEtNy0xNzkgMTEtMjcgNTgtNDggMTktNzJBMzQ5IDM0OSAwIDAgMCAzOTUgNTZ6IiBzdHlsZT0iZmlsbDojMzg2MGRkIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNNjc0IDE5NGMtNDAgMzItNTQgODYtNDQgMTM1IDggNzQgNDAgMTUwIDEzIDIyMy0xNiAzOC01NyA2NS05OCA2NC00OS0yMC0zNy04My00My0xMjYtNC02OSA2LTE0NS0zMS0yMDctMjUtMzQtNjgtMjAtOTgtMy0yIDQwIDIwIDg0IDI4IDEyNWw4NyAzMjdhMzQ4IDM0OCAwIDAgMCAyNDEtNDM1Yy0xMy0zNi0zMS03Mi01NS0xMDN6IiBzdHlsZT0iZmlsbDojMWRiNmVkIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJtMzEyIDcyIDE3NCA2NTgiIHN0eWxlPSJmaWxsOm5vbmU7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOjI3O3N0cm9rZS1saW5lY2FwOnJvdW5kIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNMTEwIDU4OGM2NyAxOSAxMzcgNTAgMjA4IDM0IDUyLTIxIDYxLTk3IDI0LTEzNS00Mi01NS0xMTktNzgtMTQ1LTE0NS0xOC02MCAyMS0xMzEgODQtMTQzIDIwLTYgNDEtOCA2Mi03bTI1IDg3YzMzLTE3IDg1LTM1IDEwNyA4IDMzIDU0IDI2IDEyMSAyOSAxODEgMSA0NS0xIDkyIDIwIDEzMiAyOSAzMiA3OCAzIDEwMS0yMyA0MS01MSAyNi0xMjEgMTUtMTc5LTExLTU3LTMwLTEyNCA3LTE3NiA3LTExIDE2LTIwIDI1LTMwIiBzdHlsZT0iZmlsbDpub25lO3N0cm9rZTojZmZmO3N0cm9rZS13aWR0aDozOSIvPjxwYXRoIHRyYW5zZm9ybT0ibWF0cml4KDEuMTAyNyAwIDAgMS4xMDMzOCAtNDEgLTQyKSIgZD0iTTc0NiA0MDBBMzQ2IDM0NiAwIDEgMSAyNTEgODdjMTM3LTYzIDMxOS0zMiA0MTQgOTAgNTEgNjIgODEgMTQyIDgxIDIyM3oiIHN0eWxlPSJmaWxsOm5vbmU7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOjMzO3N0cm9rZS1saW5lY2FwOnJvdW5kIi8+PC9zdmc+
```
See:
![Bildschirmfoto von 2021-05-06 23-32-36](https://user-images.githubusercontent.com/19690642/117368128-63229a80-aec3-11eb-9946-d8ee1e28bcef.png)
![Bildschirmfoto von 2021-05-06 23-32-24](https://user-images.githubusercontent.com/19690642/117368132-6453c780-aec3-11eb-9bb8-c4b75fc235c2.png)
